<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUx1fLRc\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUx1fLRc/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUx1fLRc.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUx1fLRc\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUx1fLRc\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ux1fLRc',
    'container.build_id' => 'c517df6e',
    'container.build_time' => 1760994867,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUx1fLRc');
