<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVxt8B7t\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVxt8B7t/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVxt8B7t.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVxt8B7t\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVxt8B7t\App_KernelDevDebugContainer([
    'container.build_hash' => 'Vxt8B7t',
    'container.build_id' => 'cdc6305d',
    'container.build_time' => 1761496982,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVxt8B7t');
