<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPd7AwYq\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPd7AwYq/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPd7AwYq.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPd7AwYq\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPd7AwYq\App_KernelDevDebugContainer([
    'container.build_hash' => 'Pd7AwYq',
    'container.build_id' => '3a8cc998',
    'container.build_time' => 1760994136,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPd7AwYq');
