<?php

namespace ContainerJrNw09D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCarouselImageCrudControllerdeleteEntityService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.egipcEH.App\Controller\Admin\CarouselImageCrudController::deleteEntity()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.egipcEH'] ?? $container->load('get_ServiceLocator_EgipcEHService'));

        if (isset($container->privates['.service_locator.egipcEH.App\\Controller\\Admin\\CarouselImageCrudController::deleteEntity()'])) {
            return $container->privates['.service_locator.egipcEH.App\\Controller\\Admin\\CarouselImageCrudController::deleteEntity()'];
        }

        return $container->privates['.service_locator.egipcEH.App\\Controller\\Admin\\CarouselImageCrudController::deleteEntity()'] = $a->withContext('App\\Controller\\Admin\\CarouselImageCrudController::deleteEntity()', $container);
    }
}
