<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Section extends \App\Entity\Section implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'Image_Id' => [parent::class, 'Image_Id', null, 16],
        "\0".parent::class."\0".'Page_Id' => [parent::class, 'Page_Id', null, 16],
        "\0".parent::class."\0".'Position' => [parent::class, 'Position', null, 16],
        "\0".parent::class."\0".'Text' => [parent::class, 'Text', null, 16],
        "\0".parent::class."\0".'Title' => [parent::class, 'Title', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'detailsSectionImages' => [parent::class, 'detailsSectionImages', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        'Image_Id' => [parent::class, 'Image_Id', null, 16],
        'Page_Id' => [parent::class, 'Page_Id', null, 16],
        'Position' => [parent::class, 'Position', null, 16],
        'Text' => [parent::class, 'Text', null, 16],
        'Title' => [parent::class, 'Title', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'detailsSectionImages' => [parent::class, 'detailsSectionImages', null, 16],
        'id' => [parent::class, 'id', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
