<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Page extends \App\Entity\Page implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'Name' => [parent::class, 'Name', null, 16],
        "\0".parent::class."\0".'Title' => [parent::class, 'Title', null, 16],
        "\0".parent::class."\0".'carousels' => [parent::class, 'carousels', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'messages' => [parent::class, 'messages', null, 16],
        "\0".parent::class."\0".'priceLists' => [parent::class, 'priceLists', null, 16],
        "\0".parent::class."\0".'sections' => [parent::class, 'sections', null, 16],
        "\0".parent::class."\0".'sliders' => [parent::class, 'sliders', null, 16],
        'Name' => [parent::class, 'Name', null, 16],
        'Title' => [parent::class, 'Title', null, 16],
        'carousels' => [parent::class, 'carousels', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'messages' => [parent::class, 'messages', null, 16],
        'priceLists' => [parent::class, 'priceLists', null, 16],
        'sections' => [parent::class, 'sections', null, 16],
        'sliders' => [parent::class, 'sliders', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
