nelmio_cors:
    defaults:
        origin_regex: false
        allow_origin: ['https://react-j3tl.onrender.com', 'http://localhost:5173', 'http://127.0.0.1:5173', 'https://127.0.0.1:8000']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With', 'Accept']
        expose_headers: ['Link']
        max_age: 3600
        allow_credentials: false
    paths:
        '^/api/':
            origin_regex: false
            allow_origin: ['https://react-j3tl.onrender.com', 'http://localhost:5173', 'http://127.0.0.1:5173', 'https://127.0.0.1:8000']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
            allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With', 'Accept']
            expose_headers: ['Link']
            max_age: 3600
            allow_credentials: false
